"""Configurazione del progetto.

Le variabili operative sono definite in codice Python per mantenere il progetto
semplice e leggibile. La pipeline importa queste variabili e le passa alle
funzioni di download, trasformazione, validazione ed export.

Il progetto non usa file di configurazione esterni o classi.
"""

from __future__ import annotations

PROJECT_SETTINGS = {
    "project_name": "valore_aggiunto_imprese",
    "language": "it",
    "start_year": 2008,
    "end_year": "latest",
    "paths": {
        "raw": "data/raw",
        "intermediate": "data/intermediate",
        "processed": "data/processed",
        "processed_csv": "data/processed_csv",
        "processed_json": "data/processed_json",
        "validation": "data/validation",
        "charts": "outputs/charts",
    },
    "default_countries": [
        "AT",
        "BE",
        "BG",
        "CY",
        "CZ",
        "DE",
        "DK",
        "EE",
        "EL",
        "ES",
        "FI",
        "FR",
        "HR",
        "HU",
        "IE",
        "IT",
        "LT",
        "LU",
        "LV",
        "MT",
        "NL",
        "PL",
        "PT",
        "RO",
        "SE",
        "SI",
        "SK",
    ],
    "metrics": [
        "value_added",
        "enterprises",
        "persons_employed",
        "employees",
        "apparent_labour_productivity",
    ],
    "output_formats": ["csv", "json"],
}

EUROSTAT_SBS_SECTORS = [
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "P",
    "Q",
    "R",
    "B05",
    "B06",
    "B07",
    "B08",
    "B09",
    "C10",
    "C11",
    "C12",
    "C13",
    "C14",
    "C15",
    "C16",
    "C17",
    "C18",
    "C19",
    "C20",
    "C21",
    "C22",
    "C23",
    "C24",
    "C25",
    "C26",
    "C27",
    "C28",
    "C29",
    "C30",
    "C31",
    "C32",
    "C33",
    "D35",
    "E36",
    "E37",
    "E38",
    "E39",
    "F41",
    "F42",
    "F43",
    "G45",
    "G46",
    "G47",
    "H49",
    "H50",
    "H51",
    "H52",
    "H53",
    "I55",
    "I56",
    "J58",
    "J59",
    "J60",
    "J61",
    "J62",
    "J63",
    "K64",
    "K65",
    "K66",
    "L68",
    "M69",
    "M70",
    "M71",
    "M72",
    "M73",
    "M74",
    "M75",
    "N77",
    "N78",
    "N79",
    "N80",
    "N81",
    "N82",
    "P85",
    "Q86",
    "Q87",
    "Q88",
    "R90",
    "R91",
    "R92",
    "R93",
    "S95",
    "S96",
]

EUROSTAT_BUSINESS_DEMOGRAPHY_SECTORS = [
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "L",
    "M",
    "N",
    "P",
    "Q",
    "R",
    "S",
    "C15",
    "C16",
    "C19",
    "C22",
    "C23",
    "C28",
    "C33",
    "G45",
    "G46",
    "G47",
    "H49",
    "H50",
    "H51",
    "H52",
    "H53",
    "I55",
    "I56",
    "J58",
    "J59",
    "J60",
    "J61",
    "J62",
    "J63",
    "K65",
    "K66",
    "L68",
    "M69",
    "M70",
    "M71",
    "M72",
    "M73",
    "M74",
    "M75",
    "N77",
    "N78",
    "N79",
    "N80",
    "N81",
    "N82",
    "P85",
    "Q86",
    "Q87",
    "Q88",
    "R90",
    "R91",
    "R92",
    "R93",
    "S94",
    "S95",
    "S96",
    "C10-C12",
    "C13_C14",
    "C17_C18",
    "C20_C21",
    "C24_C25",
    "C26_C27",
    "C29_C30",
    "C31_C32",
]

SOURCES = {
    "eurostat_sbs": {
        "source_name": "Eurostat Structural Business Statistics",
        "dataset_id": "sbs_sc_ovw",
        "base_url": "https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data",
        "note": (
            "Fonte principale per valore aggiunto, imprese e occupazione "
            "per classe dimensionale."
        ),
        "method_status": "observed_official",
        "first_year": 2021,
        "last_year": 2024,
        "filters": {
            "freq": "A",
            "indic_sbs": ["AV_MEUR", "ENT_NR", "EMP_NR", "SAL_NR", "LABPRY_TEUR"],
            "nace_r2": EUROSTAT_SBS_SECTORS,
            "size_emp": ["0-9", "10-19", "20-49", "50-249", "GE250"],
        },
    },
    "eurostat_business_demography": {
        "source_name": "Eurostat Business Demography",
        "dataset_id": "bd_9bd_sz_cl_r2",
        "base_url": "https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data",
        "note": "Fonte da verificare per distribuzioni granulari di imprese e occupati.",
        "method_status": "distribution_only",
        "first_year": 2008,
        "last_year": 2020,
        "filters": {
            "freq": "A",
            "indic_sb": ["V11910", "V16910", "V16911"],
            "nace_r2": EUROSTAT_BUSINESS_DEMOGRAPHY_SECTORS,
            "sizeclas": ["0", "1-4", "5-9"],
        },
    },
    "eurostat_national_accounts": {
        "source_name": "Eurostat National Accounts",
        "dataset_id": "nama_10_a64",
        "base_url": "https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data",
        "note": (
            "Fonte per valore aggiunto settoriale completo, inclusi agricoltura, "
            "silvicoltura, pesca, alloggio e ristorazione."
        ),
        "method_status": "observed_official",
        "first_year": 2020,
        "last_year": 2024,
        "filters": {
            "freq": "A",
            "unit": "CP_MEUR",
            "na_item": "B1G",
        },
    },
    "eurostat_regional_gva": {
        "source_name": "Eurostat Regional Gross Value Added",
        "dataset_id": "nama_10r_3gva",
        "base_url": "https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data",
        "note": "Fonte per valore aggiunto regionale NUTS dove disponibile.",
        "method_status": "observed_official",
        "first_year": 2020,
        "last_year": 2024,
        "filters": {
            "freq": "A",
            "unit": "CP_MEUR",
            "nace_r2": [
                "TOTAL",
                "A",
                "B-E",
                "C",
                "F",
                "G-I",
                "G-J",
                "J",
                "K-N",
                "K",
                "L",
                "M_N",
                "O-Q",
                "R-U",
            ],
        },
    },
    "oecd_sdbs": {
        "source_name": "OECD Structural and Demographic Business Statistics",
        "dataset_id": "DSD_SDBSBSC_ISIC4",
        "base_url": "https://sdmx.oecd.org/public/rest/v1/data",
        "note": "Fonte OCSE da verificare in fase di implementazione.",
        "method_status": "observed_official",
    },
    "istat": {
        "source_name": "ISTAT",
        "note": "Modulo di inventario e verifica fonti italiane granulari.",
        "candidate_sources": [
            "Frame SBS",
            "Frame Territoriale",
            "Frame Territoriale Anticipato",
            "Conti economici delle imprese",
            "Microdati struttura e performance imprese",
        ],
    },
}

COUNTRIES = [
    {"code": "AT", "iso3": "AUT", "label_it": "Austria"},
    {"code": "BE", "iso3": "BEL", "label_it": "Belgio"},
    {"code": "BG", "iso3": "BGR", "label_it": "Bulgaria"},
    {"code": "CY", "iso3": "CYP", "label_it": "Cipro"},
    {"code": "CZ", "iso3": "CZE", "label_it": "Cechia"},
    {"code": "DE", "iso3": "DEU", "label_it": "Germania"},
    {"code": "DK", "iso3": "DNK", "label_it": "Danimarca"},
    {"code": "EE", "iso3": "EST", "label_it": "Estonia"},
    {"code": "EL", "iso3": "GRC", "label_it": "Grecia"},
    {"code": "ES", "iso3": "ESP", "label_it": "Spagna"},
    {"code": "FI", "iso3": "FIN", "label_it": "Finlandia"},
    {"code": "FR", "iso3": "FRA", "label_it": "Francia"},
    {"code": "HR", "iso3": "HRV", "label_it": "Croazia"},
    {"code": "HU", "iso3": "HUN", "label_it": "Ungheria"},
    {"code": "IE", "iso3": "IRL", "label_it": "Irlanda"},
    {"code": "IT", "iso3": "ITA", "label_it": "Italia"},
    {"code": "LT", "iso3": "LTU", "label_it": "Lituania"},
    {"code": "LU", "iso3": "LUX", "label_it": "Lussemburgo"},
    {"code": "LV", "iso3": "LVA", "label_it": "Lettonia"},
    {"code": "MT", "iso3": "MLT", "label_it": "Malta"},
    {"code": "NL", "iso3": "NLD", "label_it": "Paesi Bassi"},
    {"code": "PL", "iso3": "POL", "label_it": "Polonia"},
    {"code": "PT", "iso3": "PRT", "label_it": "Portogallo"},
    {"code": "RO", "iso3": "ROU", "label_it": "Romania"},
    {"code": "SE", "iso3": "SWE", "label_it": "Svezia"},
    {"code": "SI", "iso3": "SVN", "label_it": "Slovenia"},
    {"code": "SK", "iso3": "SVK", "label_it": "Slovacchia"},
]

EUROSTAT_OFFICIAL_SIZE_CLASSES = [
    {
        "original": "0-9",
        "harmonised": "0-9",
        "label_it": "0-9 occupati",
        "method_status": "observed_official",
    },
    {
        "original": "10-19",
        "harmonised": "10-19",
        "label_it": "10-19 occupati",
        "method_status": "observed_official",
    },
    {
        "original": "20-49",
        "harmonised": "20-49",
        "label_it": "20-49 occupati",
        "method_status": "observed_official",
    },
    {
        "original": "50-249",
        "harmonised": "50-249",
        "label_it": "50-249 occupati",
        "method_status": "observed_official",
    },
    {
        "original": "GE250",
        "harmonised": "250+",
        "label_it": "250 o piu occupati",
        "method_status": "observed_official",
    },
]

BUSINESS_DEMOGRAPHY_SIZE_CLASSES = [
    {
        "original": "0",
        "harmonised": "0 dip.",
        "label_it": "0 dipendenti",
        "method_status": "distribution_only",
    },
    {
        "original": "1-4",
        "harmonised": "1-4 dip.",
        "label_it": "1-4 dipendenti",
        "method_status": "distribution_only",
    },
    {
        "original": "5-9",
        "harmonised": "5-9 dip.",
        "label_it": "5-9 dipendenti",
        "method_status": "distribution_only",
    },
]

EXPERIMENTAL_FINE_SIZE_CLASSES = [
    "0",
    "1",
    "2-4",
    "5-9",
    "10-14",
    "15-19",
    "20-49",
    "50-99",
    "100-249",
    "250-499",
    "500+",
]

SECTORS = [
    {
        "sector_code_harmonised": "business_economy",
        "label_it": "Business economy",
        "eurostat_nace": "B-S_X_K",
        "oecd_isic": None,
    },
    {
        "sector_code_harmonised": "industry",
        "label_it": "Industria",
        "eurostat_nace": "B-E",
        "oecd_isic": "B-E",
    },
    {
        "sector_code_harmonised": "manufacturing",
        "label_it": "Manifattura",
        "eurostat_nace": "C",
        "oecd_isic": "C",
    },
    {
        "sector_code_harmonised": "construction",
        "label_it": "Costruzioni",
        "eurostat_nace": "F",
        "oecd_isic": "F",
    },
    {
        "sector_code_harmonised": "trade",
        "label_it": "Commercio",
        "eurostat_nace": "G",
        "oecd_isic": "G",
    },
    {
        "sector_code_harmonised": "transport",
        "label_it": "Trasporti",
        "eurostat_nace": "H",
        "oecd_isic": "H",
    },
    {
        "sector_code_harmonised": "accommodation_food",
        "label_it": "Alloggio e ristorazione",
        "eurostat_nace": "I",
        "oecd_isic": "I",
    },
    {
        "sector_code_harmonised": "information_communication",
        "label_it": "Informazione e comunicazione",
        "eurostat_nace": "J",
        "oecd_isic": "J",
    },
    {
        "sector_code_harmonised": "professional_services",
        "label_it": "Attivita professionali, scientifiche e tecniche",
        "eurostat_nace": "M",
        "oecd_isic": "M",
    },
    {
        "sector_code_harmonised": "administrative_services",
        "label_it": "Servizi amministrativi e di supporto",
        "eurostat_nace": "N",
        "oecd_isic": "N",
    },
]
