core_eu:
  - code: IT
    iso3: ITA
    label_it: Italia
  - code: FR
    iso3: FRA
    label_it: Francia
  - code: DE
    iso3: DEU
    label_it: Germania
  - code: ES
    iso3: ESP
    label_it: Spagna
  - code: NL
    iso3: NLD
    label_it: Paesi Bassi
  - code: BE
    iso3: BEL
    label_it: Belgio
  - code: AT
    iso3: AUT
    label_it: Austria
  - code: SE
    iso3: SWE
    label_it: Svezia
  - code: DK
    iso3: DNK
    label_it: Danimarca
  - code: FI
    iso3: FIN
    label_it: Finlandia
  - code: IE
    iso3: IRL
    label_it: Irlanda
  - code: PT
    iso3: PRT
    label_it: Portogallo
  - code: EL
    iso3: GRC
    label_it: Grecia
  - code: PL
    iso3: POL
    label_it: Polonia
